language: java

jdk: oraclejdk7

notifications:
  email:
    recipients:
      - krasnyanskiy.alex@gmail.com
  webhooks:
    urls: https://webhooks.gitter.im/e/57ba0193a1606d865761
    on_success: false
    on_start: false
    on_failure: always

branches:
  only: master

after_success: mvn clean test