language: java

jdk: oraclejdk7

notifications:
  email:
    recipients:
      - krasnyanskiy.alex@gmail.com
  webhooks:
    urls: https://webhooks.gitter.im/e/a1e189a32947fa7a9178
    on_success: false
    on_start: false
    on_failure: always

branches:
  only:
    - master
    - develop

after_success: mvn clean test