language: java

jdk:
- oraclejdk7

notifications:
  email:
  - o.krasnianskyi@globallogic.com
  - krasnyanskiy.alex@gmail.com
  - igor.nesterenko@globallogic.com
  - borys.timakov@globallogic.com

#env:
#  global:
#    secure: ZqkbPrUf9TsheZQ0MEAYZzThPWdJhoa9W7wlwy1oQ8rFOSaWFsx02+Fz9zrPN/V0jAvaSyZkxY8FMeAHk3n2P8tbcb/J/B0XA7wtcWC4ZIw4dKjZHhpjlVBIcGT7H+KmKyokSTuW+GNnVtWk1Et/5mnh4Z4yg3r0Px2iP3y7C3A=

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.m2

after_success:
#  - mvn clean cobertura:cobertura coveralls:cobertura
  - mvn clean test jacoco:report coveralls:report