#
# REST Client Configuration
#
# @author Alexander Krasnyanskiy
#
---
server:
  url: http://54.167.46.45/jasperserver-pro
  version: 5.6.0

  headers:
    accept: JSON
    content-type: JSON

  timeout:
    connection: 5000
    read: 5000
