# You can specify here the packages and classes
# that contain your business operations
---
packages-to-scan:
  - com.test.*
  - org.test.operation.*
classes:
  - com.jaspersoft.jasperserver.jrsh.core.operation.impl.DummyOperation