profiles:
- {
    name: local,
    url: 'http://localhost:8080/jasperserver-pro',
    username: superuser
  }
- {
    name: virtual,
    url: 'http://localhost:8080/jasperserver-pro',
    username: superuser,
    organization: organization_1
  }
- {
    name: jrs-cloud,
    url: 'http://54.92.200.133/jasperserver-pro',
    username: superuser
  }
- {
    name: test,
    url: 'http://54.92.200.133/jasperserver-pro',
    username: test
  }