#
# REST Client Configuration
#
# @author Alexander Krasnyanskiy
#
---
server:
  url: http://172.28.146.32/jasperserver-pro
  version: 5.6.0

  headers:
    accept: JSON
    content-type: JSON

  timeout:
    connection: 5000
    read: 5000
